version: "3.9"
services:
  vegetable-app:
    build: .
    image: vegetable-order-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/vegetableDb
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
