namespace: dip-ns

# Veg Deployment
replicas: 5
deployment:
  labels:
    app: vegetable
  name: vegetable
  port: 3000

image:
  repository: bhagwat07/vegetable-app
  tag: v2.1.0

# ConfigMap: veg-config
configMap:
  MONGO_URL: "mongodb://veg-release-mongodb-svc:27017/vegetable_order_app"
  MONGO_INITDB_DATABASE: "vegetable_order_app"

# Veg Service
service:
  type: LoadBalancer
  port: 80
  targetPort: 3000
  protocol: TCP
  app: vegetable

#MongoDB Deployment
mongodb:
  replicas: 1
  serviceName: mongodb-svc
  app: mongodb
  containerName: mongodb-container
  repository: mongo
  tag: latest
  port: 27017
  volume:
    name: mongo-data
    mountPath: /data/db
    accessMode: ReadWriteOnce
    size: 1Gi

#MongoDB Service
mongodb_service:
  app: mongodb
  port: 27017
  targetPort: 27017
  protocol: TCP
  clusterIP: None

# StorageClass: veg-sc
 
#veg-mongodb-pvc
pvc:
  accessMode: ReadWriteOnce
  size: 2Gi
