apiVersion: apps/v1
kind: Deployment
metadata:
  name: omkar-deployment
  namespace: omkar-ns

spec:
  replicas: 5
  selector:
    matchLabels:
      app: vegetable
  
  template:
    metadata:
      labels:
        app: vegetable

    spec:
      containers:
        - name: vegetable
          image: omkartakalkar/vegetable-app:v2.0.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: veg-config
                  key: MONGO_URL
